CREATE SEQUENCE VEHICLES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_VEHICLES (
    ID INTEGER DEFAULT VEHICLES_SEQ.NEXTVAL NOT NULL,
    LICENSE_PLATE VARCHAR(100) NOT NULL,
    TYPE VARCHAR(100) NOT NULL
);

